import { FastifyInstance } from "fastify";
import healthRoutes from "./health/routes";
import authRoutes from "./auth/routes";
import sectionsRoutes from "./sections/routes";
import galleryRoutes from "./gallery/routes";
import metricsRoutes from "./metrics/routes";
import heroRoutes from "./hero/routes";
import reviewRoutes from "./review/routes";
import brandsRoutes from "./brands/routes";
import celebritiesRoutes from "./celebrities/routes";
import sellersRoutes from "./sellers/routes";
import buyersRoutes from "./buyers/routes";
import timelineRoutes from "./timeline/routes";
import archesRoutes from "./arches/routes";
import stallsRoutes from "./stalls/routes";
import buyerMosaicRoutes from "./buyer-mosaic/routes";
import vvipRoutes from "./vvip/routes";
import foundersRoutes from "./founders/routes";
import cofoundersRoutes from "./cofounders/routes";
import teamsRoutes from "./teams/routes";
import aboutRoutes from "./about/routes";
import countsRoutes from "./counts/routes";
import dualCtaRoutes from "./dual-cta/routes";
import footerRoutes from "./footer/routes";
import contactRoutes from "./contact/routes";
import cookiesRoutes from "./cookies/routes";
import feedbackRoutes from "./feedback/routes";
import galleryDetailRoutes from "./gallery-detail/routes";
import notFoundRoutes from "./not-found/routes";
import partnerRoutes from "./partner/routes";
import privacyRoutes from "./privacy/routes";
import sponsorRoutes from "./sponsor/routes";
import termsRoutes from "./terms/routes";
import testimonialsRoutes from "./testimonials/routes";
import formsRoutes from "./forms/routes";
import submitSuccessRoutes from "./submit-success/routes";
import brandingRoutes from "./branding/routes";
import templatesRoutes from "./templates/routes";
import themeRoutes from "./theme/routes";
import notificationsRoutes from "./notifications/routes";
import userAuthRoutes from "./user-auth/routes";
import profileConfigRoutes from "./profile-config/routes";
import analyticsRoutes from "./analytics/routes";
import digestsRoutes from "./digests/routes";
import digestLogsRoutes from "./digest-logs/routes";
import activityRoutes from "./activity/routes";
import homeLayoutRoutes from "./home-layout/routes";

export default async function registerRoutes(app: FastifyInstance) {
  await app.register(healthRoutes);
  await app.register(authRoutes);
  await app.register(sectionsRoutes);
  await app.register(galleryRoutes);
  await app.register(metricsRoutes);
  await app.register(heroRoutes);
  await app.register(reviewRoutes);
  await app.register(brandsRoutes);
  await app.register(celebritiesRoutes);
  await app.register(sellersRoutes);
  await app.register(buyersRoutes);
  await app.register(timelineRoutes);
  await app.register(archesRoutes);
  await app.register(stallsRoutes);
  await app.register(buyerMosaicRoutes);
  await app.register(vvipRoutes);
  await app.register(foundersRoutes);
  await app.register(cofoundersRoutes);
  await app.register(teamsRoutes);
  await app.register(aboutRoutes);
  await app.register(countsRoutes);
  await app.register(dualCtaRoutes);
  await app.register(footerRoutes);
  await app.register(contactRoutes);
  await app.register(cookiesRoutes);
  await app.register(feedbackRoutes);
  await app.register(galleryDetailRoutes);
  await app.register(notFoundRoutes);
  await app.register(partnerRoutes);
  await app.register(privacyRoutes);
  await app.register(sponsorRoutes);
  await app.register(termsRoutes);
  await app.register(testimonialsRoutes);
  await app.register(formsRoutes);
  await app.register(submitSuccessRoutes);
  await app.register(brandingRoutes);
  await app.register(templatesRoutes);
  await app.register(themeRoutes);
  await app.register(notificationsRoutes);
  await app.register(userAuthRoutes);
  await app.register(profileConfigRoutes);
  await app.register(analyticsRoutes);
  await app.register(digestsRoutes);
  await app.register(digestLogsRoutes);
  await app.register(activityRoutes);
  await app.register(homeLayoutRoutes);
}
